# <copyright file="CRLF2LF.py" company="River-Mochi">
# Copyright (c) 2026 River-Mochi. All rights reserved.
# Licensed under the MIT License. You may not use this file except in compliance with this License.
# See LICENSE file in the project root for full license information.
# This notice and the MIT License notice must be kept with
# all copies or substantial portions of this code.
# ================= </copyright> ======================

# File: Scripts/CRLF2LF.py
# Version: 0.4.1
# Purpose: 
#   River-Mochi Shared Lib file to check/fix line endings, final newline, and UTF-8 BOM.
#
# policy for VS2026 + GitHub:
#   - Only Git-tracked files are scanned.
#   - Binary-looking files are skipped.
#   - .sln stays CRLF and is NEVER touched.
#   - .slnx is LF
#   - .bat and .cmd stay CRLF and are NEVER touched by this script.
#   - UTF-8 BOM is removed automatically when --fix is used.
#   - Non-empty files without a trailing LF get one appended, matching:
#       insert_final_newline = true
#
# Notes:
#   - UI/types/ is skipped because it is generated by the CS2 UI toolchain.
#   - This script does not use .gitattributes directly. Keep extension
#     lists below aligned with each repo's .gitattributes.
#
# Usage:
#   Check only, no writes:
#     py -3 Scripts/CRLF2LF.py
#
#   Fix files:
#     py -3 Scripts/CRLF2LF.py --fix

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

UTF8_BOM = b"\xef\xbb\xbf"

# ---------------------------------------------------------------------------
# File policy
# ---------------------------------------------------------------------------

# Exact file names that are LF text files even though they may not have suffixes.
# Example: Path(".editorconfig").suffix is empty, so these need name matching.
LF_TEXT_NAMES = {
    ".editorconfig",
    ".gitattributes",
    ".gitignore",
}

# File extensions that should be LF.
# Keep this aligned with the repo's .gitattributes.
LF_TEXT_EXTENSIONS = {
    ".bash",
    ".config",
    ".cs",
    ".csproj",
    ".css",
    ".html",
    ".js",
    ".jsx",
    ".json",
    ".jsonc",
    ".md",
    ".mjs",
    ".props",
    ".ps1",
    ".pubxml",
    ".py",
    ".resx",
    ".ruleset",
    ".scss",
    ".sh",
    ".slnx",
    ".svg",
    ".targets",
    ".toml",
    ".ts",
    ".tsx",
    ".txt",
    ".xml",
    ".yaml",
    ".yml",
}

# These extensions intentionally remain CRLF.
# Visual Studio still expects .sln to be CRLF, and Windows scripts should stay CRLF.
CRLF_EXTENSIONS = {
    ".sln",
    ".bat",
    ".cmd",
}

# Folder names that should never be scanned.
# This is path-part matching, so "UI/types/foo.d.ts" is skipped because one
# path segment is exactly "types".
SKIP_PARTS = {
    ".git",
    ".vs",
    "bin",
    "obj",
    "node_modules",
    "packages",

    # CS2 API / create-csii-ui-mod generated declarations.
    # These are toolchain output, not hand-written source.
    "types",
}


# ---------------------------------------------------------------------------
# Git helpers
# ---------------------------------------------------------------------------

def run_git(args: list[str], cwd: Path) -> bytes:
    """Run a git command and return stdout.

    Exits with a readable error if git is missing or the command fails.
    """
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=cwd,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    except FileNotFoundError:
        print("ERROR: git was not found on PATH.", file=sys.stderr)
        raise SystemExit(2)
    except subprocess.CalledProcessError as ex:
        message = ex.stderr.decode("utf-8", errors="replace").strip()
        if message:
            print(f"ERROR: git {' '.join(args)} failed:\n{message}", file=sys.stderr)
        else:
            print(f"ERROR: git {' '.join(args)} failed.", file=sys.stderr)
        raise SystemExit(2)

    return result.stdout


def get_repo_root() -> Path:
    """Return the current Git repository root."""
    output = run_git(["rev-parse", "--show-toplevel"], Path.cwd())
    return Path(output.decode("utf-8", errors="replace").strip())


def get_tracked_files(repo_root: Path) -> list[Path]:
    """Return all Git-tracked files as paths relative to the repo root.

    Using git ls-files avoids accidentally rewriting untracked/generated junk.
    The -z form safely handles filenames with spaces.
    """
    output = run_git(["ls-files", "-z"], repo_root)
    names = [
        name
        for name in output.decode("utf-8", errors="replace").split("\0")
        if name
    ]

    return [Path(name) for name in names]


# ---------------------------------------------------------------------------
# File selection
# ---------------------------------------------------------------------------

def should_skip_path(relative_path: Path) -> bool:
    """Return True if this path should never be touched."""
    lower_parts = {part.lower() for part in relative_path.parts}

    # Skip generated/local folders anywhere in the path.
    if lower_parts & SKIP_PARTS:
        return True

    # Skip intentionally-CRLF file types.
    suffix = relative_path.suffix.lower()
    if suffix in CRLF_EXTENSIONS:
        return True

    return False


def is_supported_lf_text_file(relative_path: Path) -> bool:
    """Return True if this tracked file is expected to be LF text."""
    if should_skip_path(relative_path):
        return False

    name = relative_path.name.lower()
    suffix = relative_path.suffix.lower()

    return name in LF_TEXT_NAMES or suffix in LF_TEXT_EXTENSIONS


def looks_binary(data: bytes) -> bool:
    """Very simple binary guard.

    Text files should not contain NUL bytes. This is intentionally conservative.
    """
    return b"\0" in data


# ---------------------------------------------------------------------------
# Normalization
# ---------------------------------------------------------------------------

def normalize_to_lf_and_remove_bom(data: bytes) -> bytes:
    """Remove UTF-8 BOM, then normalize CRLF or mixed endings to LF."""
    if data.startswith(UTF8_BOM):
        data = data[len(UTF8_BOM):]

    # Order matters:
    #   CRLF -> LF first, then any stray CR -> LF.
    return data.replace(b"\r\n", b"\n").replace(b"\r", b"\n")


def ensure_final_newline(data: bytes) -> bytes:
    """Append a trailing LF when a non-empty file is missing one."""
    if not data or data.endswith(b"\n"):
        return data

    return data + b"\n"


def normalize_text_file(data: bytes) -> bytes:
    """Apply all safe text normalizations used by this script."""
    data = normalize_to_lf_and_remove_bom(data)
    data = ensure_final_newline(data)
    return data


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Safely check/fix LF endings for supported Git-tracked text files."
    )

    parser.add_argument(
        "--fix",
        action="store_true",
        help="Rewrite supported LF text files that have CRLF, mixed endings, missing final LF, or UTF-8 BOM.",
    )

    return parser.parse_args()


def main() -> int:
    args = parse_args()
    write_files = args.fix

    repo_root = get_repo_root()
    tracked_files = get_tracked_files(repo_root)

    changed: list[Path] = []
    skipped_binary: list[Path] = []

    for relative_path in tracked_files:
        if not is_supported_lf_text_file(relative_path):
            continue

        full_path = repo_root / relative_path

        try:
            original_data = full_path.read_bytes()
        except OSError as ex:
            print(f"WARNING: Could not read {relative_path}: {ex}", file=sys.stderr)
            continue

        if looks_binary(original_data):
            skipped_binary.append(relative_path)
            continue

        new_data = normalize_text_file(original_data)

        if new_data == original_data:
            continue

        changed.append(relative_path)

        if write_files:
            full_path.write_bytes(new_data)

    print_report(changed, skipped_binary, write_files)

    # In check-only mode, changed files should fail the command so CI/scripts can detect it.
    return 1 if changed and not write_files else 0


def print_report(changed: list[Path], skipped_binary: list[Path], write_files: bool) -> None:
    """Print a clear check/fix summary."""
    if write_files:
        if changed:
            print("Fixed line endings, final newline, and/or UTF-8 BOM:")
            for path in changed:
                print(f"  {path.as_posix()}")
        else:
            print("No line-ending, final-newline, or UTF-8 BOM fixes needed.")
    else:
        if changed:
            print("These supported LF files need line-ending, final-newline, and/or UTF-8 BOM fixes:")
            for path in changed:
                print(f"  {path.as_posix()}")
            print()
            print("No files were changed. Run with --fix to write changes.")
        else:
            print("No line-ending, final-newline, or UTF-8 BOM fixes needed.")

    if skipped_binary:
        print()
        print("Skipped binary-looking tracked files:")
        for path in skipped_binary:
            print(f"  {path.as_posix()}")


if __name__ == "__main__":
    raise SystemExit(main())
    